[2024-05-01T13:56:34.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:56:34.177+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:27.213475+00:00 [queued]>
[2024-05-01T13:56:34.185+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:27.213475+00:00 [queued]>
[2024-05-01T13:56:34.185+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:56:34.230+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): best_performing_model> on 2024-05-01 13:56:27.213475+00:00
[2024-05-01T13:56:34.249+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:56:34.253+0000] {standard_task_runner.py:63} INFO - Started process 142 to run task
[2024-05-01T13:56:34.254+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'best_performing_model', 'manual__2024-05-01T13:56:27.213475+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmp7t7uii1p']
[2024-05-01T13:56:34.261+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask best_performing_model
[2024-05-01T13:56:34.381+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:27.213475+00:00 [running]> on host cab22781d943
[2024-05-01T13:56:34.672+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='best_performing_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:56:27.213475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:56:27.213475+00:00'
[2024-05-01T13:56:34.676+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:56:34.678+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-01T13:56:34.702+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-05-01T13:56:34.703+0000] {branch.py:36} INFO - Branch into False
[2024-05-01T13:56:34.703+0000] {skipmixin.py:178} INFO - Following branch False
[2024-05-01T13:56:34.723+0000] {skipmixin.py:246} INFO - Skipping tasks [('True', -1)]
[2024-05-01T13:56:34.824+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:56:34.870+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=best_performing_model, execution_date=20240501T135627, start_date=20240501T135634, end_date=20240501T135634
[2024-05-01T13:56:34.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:56:34.996+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:56:35.020+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
