[2024-05-01T13:52:57.831+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:52:57.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:52:57.835+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:52:57.834+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:52:57.840+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:52:57.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:52:57.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:52:57.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.082 seconds
[2024-05-01T13:53:28.057+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:28.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:53:28.102+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:53:28.098+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:28.118+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:53:28.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:53:28.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:28.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.225 seconds
[2024-05-01T13:53:58.832+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:58.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:53:58.835+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:53:58.835+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:58.839+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:53:58.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:53:58.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:53:58.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2024-05-01T13:54:29.344+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:29.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:54:29.348+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:54:29.347+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:29.354+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:54:29.352+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:54:29.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:29.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.091 seconds
[2024-05-01T13:54:59.869+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:59.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:54:59.882+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:54:59.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:59.890+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:54:59.887+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:54:59.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:54:59.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.115 seconds
[2024-05-01T13:55:30.252+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:55:30.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:55:30.274+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:55:30.274+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:55:30.279+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:55:30.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:55:30.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:55:30.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.086 seconds
[2024-05-01T13:56:00.567+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:00.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:56:00.672+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:56:00.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:00.684+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:56:00.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:56:00.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:00.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.183 seconds
[2024-05-01T13:56:31.558+0000] {processor.py:161} INFO - Started process (PID=493) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:31.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:56:31.683+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:56:31.683+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:31.692+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:56:31.690+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:56:31.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:56:31.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.313 seconds
[2024-05-01T13:57:02.120+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:02.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:57:02.123+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:02.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:02.126+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:02.125+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:57:02.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:02.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2024-05-01T13:57:32.410+0000] {processor.py:161} INFO - Started process (PID=623) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:32.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:57:32.414+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:32.413+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:32.419+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:32.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:57:32.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:32.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.155 seconds
[2024-05-01T13:57:41.000+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:41.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:57:41.085+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:41.084+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:41.089+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:57:41.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:57:41.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:57:41.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.204 seconds
[2024-05-01T13:58:11.869+0000] {processor.py:161} INFO - Started process (PID=721) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:11.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:58:11.873+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:58:11.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:11.880+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:58:11.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:58:11.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:11.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.080 seconds
[2024-05-01T13:58:42.806+0000] {processor.py:161} INFO - Started process (PID=784) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:42.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:58:42.824+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:58:42.823+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:42.827+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:58:42.826+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:58:42.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:58:42.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.102 seconds
[2024-05-01T13:59:13.498+0000] {processor.py:161} INFO - Started process (PID=847) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:13.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:59:13.501+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:59:13.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:13.504+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:59:13.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:59:13.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:13.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.072 seconds
[2024-05-01T13:59:43.621+0000] {processor.py:161} INFO - Started process (PID=910) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:43.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T13:59:43.654+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:59:43.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:43.657+0000] {logging_mixin.py:188} INFO - [2024-05-01T13:59:43.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T13:59:43.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T13:59:43.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.092 seconds
[2024-05-01T14:00:14.004+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:14.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:00:14.006+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:00:14.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:14.010+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:00:14.009+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:00:14.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:14.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.068 seconds
[2024-05-01T14:00:44.400+0000] {processor.py:161} INFO - Started process (PID=1030) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:44.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:00:44.434+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:00:44.432+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:44.448+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:00:44.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:00:44.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:00:44.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.112 seconds
[2024-05-01T14:01:14.839+0000] {processor.py:161} INFO - Started process (PID=1090) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:14.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:01:14.842+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:01:14.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:14.845+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:01:14.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:01:14.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:14.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.098 seconds
[2024-05-01T14:01:46.037+0000] {processor.py:161} INFO - Started process (PID=1153) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:46.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:01:46.042+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:01:46.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:46.048+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:01:46.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:01:46.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:01:46.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.085 seconds
[2024-05-01T14:02:16.326+0000] {processor.py:161} INFO - Started process (PID=1216) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:16.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:02:16.328+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:02:16.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:16.332+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:02:16.331+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:02:16.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:16.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2024-05-01T14:02:47.663+0000] {processor.py:161} INFO - Started process (PID=1278) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:47.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:02:47.683+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:02:47.683+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:47.688+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:02:47.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:02:47.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:02:47.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.102 seconds
[2024-05-01T14:03:17.973+0000] {processor.py:161} INFO - Started process (PID=1341) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:17.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:03:17.976+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:03:17.975+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:17.990+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:03:17.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:03:17.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:18.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.250 seconds
[2024-05-01T14:03:48.521+0000] {processor.py:161} INFO - Started process (PID=1399) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:48.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:03:48.540+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:03:48.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:48.546+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:03:48.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:03:48.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:03:48.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.123 seconds
[2024-05-01T14:04:18.987+0000] {processor.py:161} INFO - Started process (PID=1462) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:18.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:04:18.992+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:04:18.992+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:18.999+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:04:18.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:04:19.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:19.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.187 seconds
[2024-05-01T14:04:49.234+0000] {processor.py:161} INFO - Started process (PID=1524) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:49.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:04:49.251+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:04:49.250+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:49.257+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:04:49.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:04:49.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:04:49.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.096 seconds
[2024-05-01T14:05:20.088+0000] {processor.py:161} INFO - Started process (PID=1587) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:20.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:05:20.093+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:05:20.092+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:20.100+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:05:20.098+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:05:20.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:20.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.083 seconds
[2024-05-01T14:05:50.734+0000] {processor.py:161} INFO - Started process (PID=1650) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:50.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:05:50.738+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:05:50.737+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:50.744+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:05:50.742+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:05:50.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:05:50.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.135 seconds
[2024-05-01T14:06:20.991+0000] {processor.py:161} INFO - Started process (PID=1714) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:20.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:06:20.998+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:06:20.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:21.005+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:06:21.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:06:21.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:21.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.109 seconds
[2024-05-01T14:06:51.218+0000] {processor.py:161} INFO - Started process (PID=1777) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:51.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:06:51.223+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:06:51.222+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:51.228+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:06:51.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:06:51.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:06:51.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.080 seconds
[2024-05-01T14:07:21.948+0000] {processor.py:161} INFO - Started process (PID=1839) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:21.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:07:21.951+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:07:21.951+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:21.955+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:07:21.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:07:21.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:22.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2024-05-01T14:07:52.205+0000] {processor.py:161} INFO - Started process (PID=1898) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:52.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:07:52.208+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:07:52.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:52.211+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:07:52.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:07:52.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:07:52.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.110 seconds
[2024-05-01T14:08:22.356+0000] {processor.py:161} INFO - Started process (PID=1961) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:22.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:08:22.358+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:08:22.358+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:22.361+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:08:22.360+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:08:22.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:22.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2024-05-01T14:08:52.812+0000] {processor.py:161} INFO - Started process (PID=2020) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:52.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:08:52.816+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:08:52.815+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:52.821+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:08:52.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:08:52.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:08:52.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.130 seconds
[2024-05-01T14:09:23.322+0000] {processor.py:161} INFO - Started process (PID=2083) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:23.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:09:23.336+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:09:23.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:23.339+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:09:23.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:09:23.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:23.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.087 seconds
[2024-05-01T14:09:53.544+0000] {processor.py:161} INFO - Started process (PID=2146) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:53.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:09:53.548+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:09:53.547+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:53.553+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:09:53.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:09:53.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:09:53.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.101 seconds
[2024-05-01T14:10:24.039+0000] {processor.py:161} INFO - Started process (PID=2210) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:24.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:10:24.050+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:10:24.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:24.053+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:10:24.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:10:24.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:24.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.104 seconds
[2024-05-01T14:10:54.493+0000] {processor.py:161} INFO - Started process (PID=2273) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:54.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:10:54.513+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:10:54.511+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:54.518+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:10:54.517+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:10:54.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:10:54.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.092 seconds
[2024-05-01T14:11:25.134+0000] {processor.py:161} INFO - Started process (PID=2336) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:25.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:11:25.155+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:11:25.154+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:25.160+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:11:25.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:11:25.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:25.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.108 seconds
[2024-05-01T14:11:55.374+0000] {processor.py:161} INFO - Started process (PID=2399) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:55.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:11:55.378+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:11:55.377+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:55.382+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:11:55.381+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:11:55.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:11:55.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.181 seconds
[2024-05-01T14:12:25.682+0000] {processor.py:161} INFO - Started process (PID=2462) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:25.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:12:25.704+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:12:25.703+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:25.714+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:12:25.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:12:25.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:25.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.149 seconds
[2024-05-01T14:12:56.441+0000] {processor.py:161} INFO - Started process (PID=2525) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:56.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:12:56.444+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:12:56.444+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:56.449+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:12:56.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:12:56.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:12:56.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.071 seconds
[2024-05-01T14:13:26.813+0000] {processor.py:161} INFO - Started process (PID=2588) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:26.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:13:26.830+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:13:26.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:26.834+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:13:26.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:13:26.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:26.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.084 seconds
[2024-05-01T14:13:57.814+0000] {processor.py:161} INFO - Started process (PID=2651) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:57.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:13:57.819+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:13:57.818+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:57.823+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:13:57.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:13:57.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:13:57.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.134 seconds
[2024-05-01T14:14:28.391+0000] {processor.py:161} INFO - Started process (PID=2714) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:28.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:14:28.446+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:14:28.445+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:28.455+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:14:28.453+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:14:28.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:28.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.430 seconds
[2024-05-01T14:14:58.890+0000] {processor.py:161} INFO - Started process (PID=2777) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:58.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:14:58.894+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:14:58.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:58.899+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:14:58.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:14:58.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:14:58.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2024-05-01T14:15:29.928+0000] {processor.py:161} INFO - Started process (PID=2840) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:15:30.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:15:30.038+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:15:30.037+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:15:30.043+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:15:30.041+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:15:30.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:15:30.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.254 seconds
[2024-05-01T14:16:00.502+0000] {processor.py:161} INFO - Started process (PID=2904) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:00.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:16:00.511+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:16:00.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:00.523+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:16:00.518+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:16:00.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:00.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.118 seconds
[2024-05-01T14:16:31.285+0000] {processor.py:161} INFO - Started process (PID=2967) to work on /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:31.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-05-01T14:16:31.295+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:16:31.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:31.298+0000] {logging_mixin.py:188} INFO - [2024-05-01T14:16:31.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 36
    catchup=False as dag:   
                  ^^
SyntaxError: invalid syntax
[2024-05-01T14:16:31.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-05-01T14:16:31.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
